### ISSUE TITLE
I can get many error logs in my logfile about protobuf

### ISSUE THREAD

**Issue by hetao29** [centrifugal/centrifugo#248] opened 2018-11-01 05:21 UTC
My version is Centrifugo v2.0.1 (Go version: go1.11.1)

`{"level":"error","error":"proto: wrong wireType = 2 for field Method","time":"2018-11-01T13:17:05+08:00","message":"error decoding control command"}
{"level":"error","error":"proto: wrong wireType = 2 for field Method","time":"2018-11-01T13:17:05+08:00","message":"error handling control message"}
{"level":"error","error":"proto: wrong wireType = 2 for field Method","time":"2018-11-01T13:17:08+08:00","message":"error decoding control command"}
{"level":"error","error":"proto: wrong wireType = 2 for field Method","time":"2018-11-01T13:17:08+08:00","message":"error handling control message"}
{"level":"error","error":"proto: wrong wireType = 2 for field Method","time":"2018-11-01T13:17:11+08:00","message":"error decoding control command"}
{"level":"error","error":"proto: wrong wireType = 2 for field Method","time":"2018-11-01T13:17:11+08:00","message":"error handling control message"}
{"level":"error","error":"proto: wrong wireType = 2 for field Method","time":"2018-11-01T13:17:14+08:00","message":"error decoding control command"}`

**Comment by FZambia** [comment] 2018-11-01 06:07
Hello, please provide steps to reproduce.

**Comment by hetao29** [comment] 2018-11-01 06:12
Thanks very much , I guess may be the reason is both v1.8 and v2.1 use the same redis config.
I change v2.1's redis config to the another , the errro disappeared.

**Comment by FZambia** [comment] 2018-11-01 06:18
Yes, it can be the reason because both versions use the same channel for control messages but different format. I suppose that using custom redis_prefix in config file can help too. But better to just use different Redis insrances

**Comment by hetao29** [comment] 2018-11-01 06:37
Sorry, I cant find the redis_prefix description in the document.

**Comment by FZambia** [comment] 2018-11-01 06:54
Yep, just fixed in commit 5d7495ebbab942e48464e1deb2fbb044df22c7cc, already updated [in docs](https://centrifugal.github.io/centrifugo/server/engines/#redis-engine)

**Comment by hetao29** [comment] 2018-11-01 07:46
Thanks very much!

**Comment by FZambia** [comment] 2018-11-01 09:11
Welcome!

**Closed by FZambia** 2018-11-01 09:11 UTC

**Comment by hetao29** [comment] 2018-11-01 09:15
Error: unknown flag: --redis_prefix
~~~

**Comment by FZambia** [comment] 2018-11-01 11:10
This is not supported by command-line arguments - must be set in configuration file
