### ISSUE TITLE
[bug] 2.2.5 - remote error: tls: unknown certificate

### ISSUE THREAD

**Issue by Signorini** [centrifugal/centrifugo#323] opened 2019-12-05 17:41 UTC
**Describe the bug**
> Hello sorry for the inconvenience, I like to help but cannot install an internal dependency. I don't like to bother you again.

I try to use 2.2.5 acme, like, seems to connect and seem to work, but the handshake not happen, my port 80 its open.

<img width="810" alt="Screenshot 2019-12-05 at 17 25 19" src="https://user-images.githubusercontent.com/1161310/70258674-886a2100-1784-11ea-9ecb-22610bae1d8f.png">

Checking the browser
```
Error in connection establishment: net::ERR_CERT_INVALID
```

---

I try to install centrifuge in my machine
```
I try to fix but I've blocked by internal packages...

main.go:25:2: use of internal package projects/centrifugo/vendor/github.com/centrifugal/centrifugo/internal/admin not allowed
main.go:26:2: use of internal package projects/centrifugo/vendor/github.com/centrifugal/centrifugo/internal/api not allowed
main.go:27:2: use of internal package projects/centrifugo/vendor/github.com/centrifugal/centrifugo/internal/health not allowed
main.go:28:2: use of internal package projects/centrifugo/vendor/github.com/centrifugal/centrifugo/internal/metrics/graphite not allowed
main.go:29:2: use of internal package projects/centrifugo/vendor/github.com/centrifugal/centrifugo/internal/middleware not allowed
mai
```

…

**Versions**
> Centrifugo version is 2.2.2
> Client library used is centrifuge-socket of version 2.2.3
> Operating system is amazon linux, running on the docker

...

**Steps to Reproduce**
> Start centrifugue enabling acme http

…

**Expected behavior**
> Handshake and wss connection

…

**Code Snippets**
>
```
{
   "tls_autocert_http": true,
   "tls_autocert_http_addr": ":80"
}
```

…
thanks a million

**Comment by FZambia** [comment] 2019-12-06 05:41
Hello, will try to reproduce with my own domain.

Regarding to running Centrifugo - you need to download repo into your $GOPATH - i.e. $GOPATH/src/github.com/centrifugal/centrifugo

**Comment by Signorini** [comment] 2019-12-06 10:58
I put the project on gopath, the issue it's

```
/centrifugo/internal/admin not allowed
/centrifugo/internal/api not allowed
/centrifugo/internal/health not allowed
...
```
Like every internal package Im not allowed to get

thanks a million

**Comment by Signorini** [comment] 2019-12-06 11:31
You can close the ticket, it's a let's encrypt issue.

Like Ive used websocket.xx domain with the previous library, when I update the service to 2.2.5 the acme doesn't recognize my certs, I clean the certs and waiting let's encrypt to recreate and push back the new cert. Boom works.

sorry about this, I know it's bad.

But, I still not to be able to get an internal centrifugo packages... I like the project, the idea its great

**Comment by FZambia** [comment] 2019-12-06 11:35
@Signorini glad it works :+1: I can help you with project layout, can you post exact console commands from the beginning to reproduce errors with internal packages? Because it just works for me if I clone this repo to my $GOPATH

**Comment by FZambia** [comment] 2019-12-08 15:52
Please feel free to continue discussion here if you want help running project locally. Closing

**Closed by FZambia** 2019-12-08 15:52 UTC

**Comment by Signorini** [comment] 2019-12-09 11:07
thanks, all good.
