### ISSUE TITLE
[bug] "Too many colons in address" error in docker container setup

### ISSUE THREAD

**Issue by blumfontein** [centrifugal/centrifugo#360] opened 2020-05-02 18:23 UTC
Hello!

**Describe the bug**

When deploying centrifugo docker image with version upper than 2.0.2 to Rancher 2.x with exposed public port (i.e. 8000), it fails with the message: 
ListenAndServe: listen tcp: address :tcp://x.x.x.x:8000: too many colons in address.

When deploying without public port mapping, it launches successfully.

Related issue at Helms charts repo: https://github.com/helm/charts/issues/10609

Whole log:

```
2020-05-02T18:27:45Z |INFO| starting Centrifugo 2.1.0 (go1.11.4)
2020-05-02T18:27:45Z |INFO| config path: /centrifugo/config.json
2020-05-02T18:27:45Z |INFO| pid: 1
2020-05-02T18:27:45Z |INFO| engine: Memory
2020-05-02T18:27:45Z |INFO| gomaxprocs: 24
2020-05-02T18:27:45Z |INFO| serving websocket, SockJS, API, admin endpoints on :tcp://x.x.x.x:8000
2020-05-02T18:27:45Z |FATAL| ListenAndServe: listen tcp: address :tcp://x.x.x.x:8000: too many colons in address
```

And log without port mapping:

```
2020-05-02T18:30:08Z |INFO| starting Centrifugo 2.1.0 (go1.11.4)
2020-05-02T18:30:08Z |INFO| config path: /centrifugo/config.json
2020-05-02T18:30:08Z |INFO| pid: 1
2020-05-02T18:30:08Z |INFO| engine: Memory
2020-05-02T18:30:08Z |INFO| gomaxprocs: 24
2020-05-02T18:30:08Z |INFO| serving websocket, SockJS, API, admin endpoints on :8000
```

**Versions**

All docker image versions higher than v2.0.2. 
Operating system is Ubuntu 18.04

**Steps to Reproduce**

1. Create workload at rancher server 2.x with the image centrifugo/centrifugo:v2.1.0. 
2. Set port mapping: 8000 to 8000 tcp with HostPort option

**Expected behavior**

Launch container successfully

**Comment by FZambia** [comment] 2020-05-02 20:55
@blumfontein hi, this looks like misconfiguration, I can reproduce this locally with sth like:

```
go run main.go --port ":tcp://0.0.0.0:8000"
```

But this is simply wrong option for port. So I don't think this is a bug in Centrifugo. 

The chart you pointed to is not official (we have no official helm chart at moment).

**Comment by blumfontein** [comment] 2020-05-02 21:42
@FZambia Thank you for answer

Accidentally, I've found workaround. After setting port explicitly in the launching command it works somehow.

```
centrifugo -c config.json --port 8000 --admin
```

Best regards

**Comment by FZambia** [comment] 2020-05-03 09:13
Cool, closing since I don't think this should be fixed from Centrifugo side.

**Closed by FZambia** 2020-05-03 09:13 UTC

**Comment by FZambia** [comment] 2023-01-11 06:22
BTW, the reason for this is that Kubernetes may automatically pass env var called `CENTRIFUGO_PORT` (with address included) which clashes with Centrifugo's port option. In our Helm chart we explicitly setting port in command-line flags – so since command-line arguments has priority over environment vars Centrifugo starts correctly.
