### ISSUE TITLE
i want log gzip by date

### ISSUE THREAD

**Issue by visrs** [centrifugal/centrifugo#159] opened 2017-02-17 08:09 UTC
i want log cut by day like this
-rwxrw-rw- 1 root root   0 Feb 17 03:38 centrifugo.log
-rwxrw-rw- 1 root root 285 Feb 11 03:36 centrifugo.log-20170211.gz

how to do it？

**Comment by FZambia** [comment] 2017-02-17 08:39
Duplicate of #116 - use logrotate for this.

**Closed by FZambia** 2017-02-17 08:39 UTC
