### ISSUE TITLE
[bug] missing admin_web_path from command line

### ISSUE THREAD

**Issue by edgardmessias** [centrifugal/centrifugo#306] opened 2019-10-28 12:02 UTC
**Describe the bug**
Missing the flag "admin_web_path" from command line.
Working fine if is setted in "config.json"

**Versions**
Centrifugo version is 2.2.3
Operating system is windows

**Steps to Reproduce**
Run centrifugo with "admin_web_path"
example: `centrifugo --admin --admin_web_path=<path>`

**Expected behavior**
Current: `Error: unknown flag: --admin_web_path`
Expected: Work

**Code Snippets**
```
centrifugo --admin --admin_web_path=<path>
```

**Comment by FZambia** [comment] 2019-10-28 15:46
@edgardmessias in general it's not a bug, this is how it's supposed to be in Centrifugo v2. Only frequently used options in Centrifugo go to command-line, `admin_web_path` is used in rare cases mostly for development so it's not in flags at moment. All supported flags can be listed using `centrifugo -h`. Looks like we need to fix readme in https://github.com/centrifugal/web as it contains wrong information about `admin_web_path` option (this option was removed from flags with Centrifugo v2 release but I missed this fact when updated https://github.com/centrifugal/web README).

**Comment by FZambia** [comment] 2019-11-01 13:41
Fixed in https://github.com/centrifugal/web/commit/77cced75f7d3c74344116807484e85afa077af3d, open another issue to consider setting all options over command-line - https://github.com/centrifugal/centrifugo/issues/308

**Closed by FZambia** 2019-11-01 13:41 UTC
