### ISSUE TITLE
How to disable EVALSHA cmd  of redis

### ISSUE THREAD

**Issue by hetao29** [centrifugal/centrifugo#489] opened 2021-11-03 10:53 UTC
I get the redis slow log of this:

`
slowlog get 3
1) 1) (integer) 240
   2) (integer) 1635509994
   3) (integer) 11058
   4)  1) "EVALSHA"
       2) "c7765f51ce2895b0999ea89656615c194275baf5"
       3) "2"
       4) "centrifugov2.2.1.1.list.auction:23005"
       5) "centrifugov2.2.1.1.list.meta.auction:23005"
       6) "\"\x81\x94\x10{\"messageid\":null,\"type\":\"update_auction_item\",\"content\":\"{\\\"auction_id\\\":23005,\\\"item_id\\\":\\\"487368\\\",\\\"auction_item\\\":{\\\"i... (264581 more bytes)"
       7) "49"
       8) "300000"
       9) "centrifugov2.2.1.1.client.auction:23005"
      10) "0"
   5) "172.18.0.9:35878"
   6) ""`

**Comment by FZambia** [comment] 2021-11-03 11:46
Hello, it's impossible to disable if you want to use channel history feature. This is how Centrifugo communicates with Redis for history related stuff. If you don't need history – then you can disable it in Centrifugo configuration.

Maybe you have long history size or huge message sizes (270kb as far as I can see? This is pretty big for WebSocket communications). This can also be a sign that it's a time for you to scale up Redis. Since you have not provided any additional information I can't help further - thus closing an issue. Provide steps to reproduce if you think this is a bug in Centrifugo. Or try asking for a help in our community groups.

**Closed by FZambia** 2021-11-03 11:46 UTC

**Comment by hetao29** [comment] 2021-11-05 09:42
Hi, Is it enough to disable the history function or use the default set like this? 

```json
{
    "name": "test",
    "publish": true,
    "presence": true,
    "join_leave": true,
    "anonymous":true,
    "websocket_compression":true
}
```

**Comment by FZambia** [comment] 2021-11-05 10:23
You should disable history in configuration, the config you sent seems fine but looking at your slow log you need to disable history for `auction` namespace.

**Comment by hetao29** [comment] 2021-11-06 01:20
OK, thans very much, ^_^
