### ISSUE TITLE
[question] node connection not closed

### ISSUE THREAD

**Issue by leegun2000** [centrifugal/centrifugo#486] opened 2021-10-14 07:30 UTC
Hello
 
Appears during load test.
use websocket => connection, subscribe, unsubscribe 
use grpc API => publish

The connection does not decrease after the request is completed.

Maybe goroutine is not reduce..

![image](https://user-images.githubusercontent.com/6631488/137268251-a4272a48-ea44-4e58-ad1c-2a75b5a530bc.png)
![image](https://user-images.githubusercontent.com/6631488/137268522-8637ae76-46f9-4d1f-b463-a0ea1d490591.png)
![image](https://user-images.githubusercontent.com/6631488/137268670-12d758ab-eac0-410a-a21e-84be03f08092.png)

The number of sockets is not the same.
![image](https://user-images.githubusercontent.com/6631488/137271225-053e6162-818e-45e7-b3df-36686325b87c.png)

Centrifugo v3.3
CentOS 8 & Rocky Linux 8
my confiuration..
```
{
    "debug": true,
    "token_hmac_secret_key": "secret",
    "admin_password": "password",
    "admin_secret": "adbbac84-c8c2-4745-b409-bf2e9a4d6eb2",
    "api_key": "2cfafc0a-89b6-46ac-a323-5dfcdb950de2",
    "grpc_api_key": "grpc",
    "grpc_api_port": 10000,
    "grpc_api": true,
    "prometheus": true,
    "engine": "redis",
    "redis_address": [
      "10.1.3.15:6379"
    ],
    "history_meta_ttl": "30m",
    "api_insecure": false,
    "client_insecure": true,
    "user_subscribe_to_personal": true,
    "user_personal_single_connection": false,
    "user_personal_channel_namespace": "personal",
    "websocket_read_buffer_size": 512,
    "websocket_write_buffer_size": 512,
    "sockjs": true,
    "namespaces": [
      {
        "name": "personal"
      },
      {
        "name": "public",
        "presence": true,
        "anonymous": true,
        "history_size": 300,
        "history_ttl": "30s",
        "position": true,
        "recover": true
      }
    ],
    "allowed_origins": [
      "*"
    ]
}
```

How to handle this issue?

**Comment by FZambia** [comment] 2021-10-16 06:05
@leegun2000 thanks for a helpful information, I reproduced an issue locally (at least it seems so!) – the fix is in https://github.com/centrifugal/centrifuge/pull/208 and will be part of v3.0.4.

**Comment by leegun2000** [comment] 2021-10-16 12:48
@FZambia Thank you for your answer. I'll check when the next version comes out.

Thanks.

**Comment by FZambia** [comment] 2021-10-16 14:36
v3.0.4 just released - please check it out. Will be awesome if you share dashboard screenshots even if it goes without problem.

**Comment by leegun2000** [comment] 2021-10-17 07:34
Awesome!!
There seems to be nothing problem in v3.0.4


![1](https://user-images.githubusercontent.com/6631488/137616609-8c5d69c0-b24b-4b6e-9184-087c5619ec57.PNG)
![2](https://user-images.githubusercontent.com/6631488/137616611-6818b581-7311-408b-9a84-d97112429994.PNG)


Thank you for solving the problem quickly.

**Comment by leegun2000** [comment] 2021-10-18 05:06
Sorry, It's a result that I didn't expect.

Here's a bit of an interesting result.

![4](https://user-images.githubusercontent.com/6631488/137671865-2b95fe24-6043-4401-afab-71f6b66c98ac.PNG)

To provide a dump file, trying to reproduce it.

**Comment by leegun2000** [comment] 2021-10-19 03:47
I tried several load tests.

Didn't see the same problem as last time.

Related problem appear to have been resolved.

<img width="1401" alt="Screen Shot 2021-10-19 at 12 34 28" src="https://user-images.githubusercontent.com/6631488/137840164-1ff00d04-a564-48da-bc5f-3499e6c31d70.png">
<img width="1385" alt="Screen Shot 2021-10-19 at 12 35 04" src="https://user-images.githubusercontent.com/6631488/137840168-0a8a915e-4100-468d-a03a-c6b16b35ecd6.png">
<img width="1390" alt="Screen Shot 2021-10-19 at 12 34 55" src="https://user-images.githubusercontent.com/6631488/137840172-352a4166-be4d-4600-a995-43c0f46bab77.png">

Thank you for solving the problem.

**Comment by FZambia** [comment] 2021-10-20 10:31
Hard to say - you decide for your app. The fact that latency dropped on scale is a good sign.

For me latency still seems too big for this load. I still lack some information like Redis CPU and Redis rps to reason better. Maybe subscribe latency caused not by load on Redis but due to lock contention inside Centrifugo for this load profile. But if you scaled Redis while keeping the same amount of Centrifugo nodes (are you?) and latency dropped – then Redis is the reason I suppose.

My local tests show that Redis is capable to serve ~50k stream position sync requests per second while consuming ~80% of one CPU core. Looking at your setup with 200k connections each subscribed to 2 channels – this should produce ~10k rps on Redis thus CPU consumption I expect is ~20%. At 20% Redis should not have latencies like this. But again - it depends a lot on Redis settings used, if you are using Redis AOF then this could be expected. Scaling Redis is a way to go. Redis only uses 1 CPU core so it's normal to have several Redis instances on one machine. I suppose Redis Cluster is also a possible alternative.

Without `recover` and `position` options on you should expect much better latencies I think.

By default, Centrifugo issues history sync request once in 40 secs for each subscription with recover/position on (every message coming to channel result into sync request delay, so in channels with pretty fast message rate the amount of sync requests is zero or low). Can be tuned over `client_channel_position_check_delay` (default `40s` so you can try to make it `120s` and see what happens - but before doing this make sure Redis consumes lot of CPU due to requests to history from Centrifugo nodes).

If you want to investigate/discuss this further  - please write to Telegram or Discord [community groups](https://centrifugal.dev/docs/getting-started/introduction#join-community)), you can also write to me via PM. Or just continue writing here.

Closing an issue since the problems seem to be fixed. Many thanks for reporting – a very unfortunate and hard-to-catch bugs!

**Closed as completed by FZambia** 2021-10-20 10:31 UTC
