### ISSUE TITLE
Streaming historical data support!?

### ISSUE THREAD

**Issue by foobargeez** [centrifugal/centrifugo#166] opened 2017-03-09 07:03 UTC
As I understand, messages in channel expires past defined history expiry and when a client subscribes to a channel after the data expires, it receives either no/partial data.  There are legitimate use cases where the client needs to see historical data.  Is it possible for centrifugo client to post to a `client` channel (controlled via configuration) when `recovered` is false, which then publishes a flag to a redis data structure that we subscribe to from our backend?  This trigger makes backend look at what is available in history and it then starts to backfill the data and post it to the same `client` channel that the user subscribed to.

The above helps us avoid writing two branches of code in the client app - (1) to consume channel data and monitor for `recovered` (2) when `recovered` is false, call backend explicitly.  The above use case, if you think is worth looking into, will help us rely on centrifugo channel soley for consuming messages.

The above is one suggestion for the implementation but despite the practicality/efficiency of it, the underlying requirement/use case has value I suppose.  This is in a way akin to [NATS streaming](http://nats.io/documentation/streaming/nats-streaming-intro/) but without centrifugo getting into/avoiding the headache of storage and/or how backend populates history.

Let me know if something is unclear.

**Comment by FZambia** [comment] 2017-03-09 21:17
@foobargeez hello. I think I don't understand - what is the disadvantage of calling backend explicitly for messages when `recovered` is `false`?  You can call backend and then start backfilling messages posting them to client channel like you suggested (but I'd just return all messages in response to backend call). For me this is the same what you suggest but without extra `magic` message posting into channel and without involving Redis.

**Comment by foobargeez** [comment] 2017-03-09 23:20
I was thinking/hoping to leverage centrifugo as a broker to communicate with our backend which then helps me to just deal with centrifugo and not call the backend explicitly (and deal with timeouts/failures/all the fun that comes with handling REST endpoints).

If not a magic message post to redis, something like supporting a RPC call too would work akin to [deepstream's RPC](https://deepstream.io/tutorials/core/request-response-rpc/).  I think RPC route is more generic and scalable.

Let me know if we are on the same page.  If not, I am happy to jump into gitter and see if I can convince you :-)

**Comment by FZambia** [comment] 2017-03-10 09:38
I understand that having RPC built into real-time framework is a huge win - you provide a builtin way for users to utilize already setup websocket connection to call backend functions. But this is OK for framework - you can register your backend-side functions leveraging deep integration of real-time framework with your application code. 

But Centrifugo can't be a framework as it was designed to work with all backend languages. Calling backend function in this case is not just a delivering RPC message from client to Centrifugo but also asking backend over HTTP from Centrifugo side then - I see some disadvantages in this approach:

* longer way for message to travel until we get response - instead of 1 RTT to backend we get 2 hops from client to Centrifugo, then from Centrifugo to backend and then back. Having this feature in Centrifugo looks as making our users using anti-pattern where it's possible to just explicitly call backend for RPC-like information. Especially with HTTP 1.1 connection keep-alive and HTTP/2 this does not look like a huge overhead.
* at moment Centrifugo has no knowledge about application backend at all - even URL address, I think it's a good thing to have this loose coupling and want to keep this this way until possible
* the fact that you won't deal with timeouts means that Centrifugo will need to deal with them and other HTTP handling stuff - this is additional proxy logic in Centrifugo core I'd like to avoid - I like current one-directional data flow concept from app backend to client through Centrifugo

Does it make sense?

Also have you looked at [Pushpin](https://github.com/fanout/pushpin) - it looks like real-time proxy that maybe better suits your needs.

**Comment by foobargeez** [comment] 2017-03-11 04:11
Thanks for your thoughts.  The issue really for me is that Centrifugo doesn't support historical message replays in a given channel and that the mobile app needs to have a plan B to circumvent that (it can be good or bad depending on how one sees it).  My preference at the moment is to rely on one thing (thing being a black box for now) and let that handle delivering recent messages quickly and historical messages albeit slowly (relatively).

I understand that Centrifugo uses redis for storing messages (and storing tons of data in RAM isn't exactly free/a great idea) but having support for more than redis to replay historical data _really_ helps.  If Centrifugo supports historical message replays, redis, will assume a cache role, to deliver recent messages (and quickly) and beyond that for historical data, Centrifugo queries an external database, be it Tarantool or Elasticsearch or simply external files based or whatever connectors you/community comes up with.  If you were to add support for an external database for historical data, I can't see how this can be a uni-directional data flow, as the client needs to listen for "requesting more data" and has to be passed to the server somehow as sending "all" data is sometimes be expensive and the client may not just want it or can't handle it.

If you were to stick with uni-directional data flow though, then may be, your idea of supporting external database could just be to replace redis but not necessarily in conjunction with redis and at least not for historical data.

The alternative to supporting external database for historical data is to support ability to just call REST endpoints with RPC support, although at the expense of uni-direction data flow, which you want to avoid, so not getting into it.

I agree with your note about two hops, but I didn't think that would be a big deal (as far as elapsed time from user's perspective) if the client were to proactively read ahead data, so by the time the user wants historical data, it's ready for him.

I came across [pushpin](https://github.com/fanout/pushpin) in the past and it's on my list to things to look into, especially if Centrifugo doesn't support historical message replays.  I am not a big fan of too many moving parts/technologies -- hurts reliability at some point and pretty badly -- although I understand that sometimes you can't avoid that.

If you were to say that replaying historical messages is not on your priority list though, I guess I will look around for other complimentary solutions to see if there is something that meets my requirements.  Appreciate your time and discussion!

**Comment by foobargeez** [comment] 2017-03-11 07:11
Thinking more ... historical message replay is more likely a requirement by a particular client at a given time (or multiple clients at the same time for different date/time duration criteria) and having the historical messages being pushed to the same channel that all clients are connected isn't probably efficient, as we end up pushing more data to clients that don't really care for it (I don't really know if there is a way for the client to discard the data that it is not expecting though, so to not have any additional overhead of processing the data that it doesn't want).

Given the above concerns, I don't think on-demand data pushing for a single client to a channel where all clients are connected to, is efficient.  I would ideally prefer Tarantool/Elasticsearch (given their cluster abilities) for storing all the data (both new and historical) and have Centrifugo deliver messages in a streamed fashion (akin to NATS streaming).  This way, the client will connect to Centrifugo for all it's messaging needs and be (mostly) done.

Supporting Tarantool/Elasticsearch as external storage will give me more flexibility as I can independently push data to those stores i.e., outside Centrifugo (Centrifugo reads from it, as it does from redis right now).

NATS streaming is the closest to my requirements but I am not a big fan of file based stores, so supporting Tarantool/Elasticsearch/some DB that has cluster ability (and HA) will be a huge benefit.  Also, NATS lacks presence information and leave/join events that Centrifugo has.  So, I am looking for what Centrifugo does but replace Redis with an external DB (for data storage at least) and support streaming data.

Thanks for the discussion -- I am now more clear on what I am looking for :-)

BTW, if you agree with the above (even not fully) and are willing to put in hours and I will certainly consider swallowing some of the development costs (do let me know your email and we shall discuss further).

Let me know if something is unclear and I am happy to elaborate.

**Comment by foobargeez** [comment] 2017-03-11 07:38
I was going through https://github.com/centrifugal/centrifugo/issues/45 and came across this by @banks:

> I'd actually suggest if we were to consider that, that we should make pubsub part a separate engine from storage part so you could write custom providers for that but. For example NATS.io, NSQ, RabbitMQ or Kafka for pubsub with DB X for storage of history etc.

The above is very close to what I was proposing above -- Redis (or some other provider) for pub-sub and an external DB for channel data (current and/or historical).

**Comment by FZambia** [comment] 2017-04-07 16:53
Closing after discussion here and in Gitter - currently there are no plans to provide reliable message replay from persistent store directly in Centrifugo core. At moment this can theoretically be another system near Centrifugo (to reuse in many apps) or just a specific application backend. Maybe in future we come back to this topic, will see, the idea described in this issue is reasonable but I don't see a straight way to implement it on top of what we have now.

**Closed by FZambia** 2017-04-07 16:53 UTC
