### ISSUE TITLE
206 Partial Content when loading web interface js bundle

### ISSUE THREAD

**Issue by iamsee** [centrifugal/centrifugo#249] opened 2018-11-27 00:29 UTC
![image](https://user-images.githubusercontent.com/6944557/49050493-8e96fa80-f21e-11e8-8008-77a9ec82755a.png)

version: 2.0.1+

**Comment by FZambia** [comment] 2018-11-27 07:30
Closing as this is wrong repo and no information provided. Open issue in centrifuge-js and provide steps to reproduce.

**Comment by FZambia** [comment] 2018-11-27 07:34
I saw this error during development but I thought it was gulp issue. Are you using builtin web interface without custom `admin_web_path`?

**Comment by iamsee** [comment] 2018-12-03 09:21
yep, not use custom admin_web_path , just the builtin

**Comment by FZambia** [comment] 2018-12-10 09:20
@iamsee unfortunately I can't reproduce this at moment even in development... Let's keep this open for now - at least until https://github.com/centrifugal/web/issues/13 will be closed.

**Comment by FZambia** [comment] 2018-12-30 14:58
In Centrifugo [v2.1.0](https://github.com/centrifugal/centrifugo/releases/tag/v2.1.0) I've rewritten web interface using modern JS stack, hopefully the problem will go away. @iamsee please check it out and reopen if the problem still remains in v2.1.0

**Closed by FZambia** 2018-12-30 14:58 UTC
