### ISSUE TITLE
v2.2.0 websocket bug 

### ISSUE THREAD

**Issue by hetao29** [centrifugal/centrifugo#279] opened 2019-04-15 09:03 UTC
{"level":"debug","method":"POST","path":"/admin/api","addr":"43.228.36.46:35570","duration":0.49352,"time":"2019-04-15T16:51:52+08:00","message":"http request"}
{"level":"error","error":"ERR Error running script (call to f_50c6939aa2b1873bfb20bc1c4d14087ed78e947c): @user_script:2: user_script:2: attempt to call field 'replicate_commands' (a nil value) ","time":"2019-04-15T16:51:52+08:00","message":"error calling history"}

**Comment by FZambia** [comment] 2019-04-15 09:05
Hello, please describe steps to reproduce. Also what Redis server version are you using?

**Comment by hetao29** [comment] 2019-04-15 09:13
I find that change the redis_prefix in config file is ok.

I test that 2.1.x,2.0.x is compatible.

redis version:
```bash
Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=28b6715d3583bf8e
```

**Comment by hetao29** [comment] 2019-04-15 09:26
The v2.2.0 change the new redis_prefix is and restart will be ok, and few api actions later, the websocket will not work.

**Comment by FZambia** [comment] 2019-04-15 09:40
Sorry - to make things more clear - do you mean that the issue only reproduces in v2.2.0?

**Comment by hetao29** [comment] 2019-04-15 09:58
The bug only in v2.2.0.

**Comment by hetao29** [comment] 2019-04-15 10:03
The step how to show the bug of me:
1. run 2.2.0 app
2.connect the websocket with the js code
```javascript
  this.connect = (config, callback = {}) => {
    conf = config;
    call = callback;
    id = 1;//重置计数器，连接的时候就可以正常订阅
    socket = new WebSocket();
    socket.onOpen((res) => {
      var data = {
        "method": "connect",
        "params": config.params,
        "id": getUniqueId()
      }
      send(data, callback);
      if (callback.onOpen) {
        callback.onOpen(res)
      }
    });
    socket.onClose((res) => {
      console.log("onSocketClose");
      if (callback.onClose) {
        callback.onClose(res)
      }
    });
    socket.onError((res) => {
      console.log("onSocketError");
      if (callback.onFail) {
        callback.onFail(res)
      }
    });
    socket.onMessage((res) => {
     // console.log("onMessage")
      let resdata = res.data.split("\n");
      for (var i in resdata) {
        if (resdata[i]) {
          try {
            var message = JSON.parse(resdata[i])
            if (message.id) {
              if (message.id == 1) {

                var data = {
                  "method": "subscribe",
                  "params": {
                    "channel": config.channel
                  },
                  "id": getUniqueId()
                }
                send(data, callback);
                return;
              }
            } else {
              if (message.result.type == 1) {//join
                if (config.onJoin && message.result.data) {
                  config.onJoin(message.result.data)
                }
              } else
                if (message.result.type == 2) {//leave
                  if (config.onLeave && message.result.data) {
                    config.onLeave(message.result.data)
                  }
                } else if (message.result.type == 3) {//Unsub
                  if (config.onLeave && message.result.data) {
                    config.onLeave(message.result.data)
                  }
                } else {
                  if (config.onData && message.result.data) {
                    config.onData(message.result.data)
                  }
                }
            }
          } catch (e) {
            console.log(e)
          }
        }
      }
    })
  }
```
3.send the msg from api server to message server, the message will be broadcast, and the client will be received.
4.but ,disconnect the websocket and retry from the step 2, the client will not get the new message.

**Comment by FZambia** [comment] 2019-04-15 10:36
You need to use Redis v3.2.x to get rid of `user_script:2: attempt to call field 'replicate_commands' (a nil value)` error. But this was the same since Centrifugo v2.0.0. I will add recommended Redis version to docs.

You posted a custom client code and changed issue title - are you going to say that we now talk about another issue that is not related to Redis? Why are you using hand-written Javascript client instead of using [centrifuge-js](https://github.com/centrifugal/centrifuge-js)? Could you reproduce an issue with our official Javascript client?

**Comment by hetao29** [comment] 2019-04-15 11:36
I test my program with the redis v5, It's ok!


And the problem of v2.2.0 exists, v2.1.x not exists.
When I publish message from server , the client with the same channel websocket will be reset.

the is my js code with js sdk
```javascript

  | <html>
-- | --
  | <head>
  | <script src="/assets_v4/js/centrifuge.min.js"></script>
  | </head>
  | <body>
  | <script>
  | /**
  | *https://github.com/centrifugal/centrifuge-js
  | */
  | var centrifuge = new Centrifuge('ws://dev.xxx.com:8012/connection/websocket');
  | centrifuge.setToken("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaW5mbyI6eyJ1aWQiOjEsIm5hbWUiOiJOYW1lIiwidGh1bWIiOiJ4eCJ9fQ.UiQTGdAQ4vqS5CpwRqIPcRgFZ4Dw8DMNPISqpLRVgxY");
  |  
  | centrifuge.subscribe("planv2:3", function(message) {
  | console.log(message);
  | });
  |  
  | centrifuge.connect();
  |  
  | </script>
  | </body>
  |  
  | </html>
  |  


```

this is the api code of php
```php
    public static function broadcast($planv2_id, $message ,&$res){
        //向 API 增加消息
        //广播消息
        $config = SConfig::getConfig(ROOT_CONFIG . "/messagev2.conf", "planv2");
        $client = new \phpcent\Client($config->url_backend);
        $client->setApikey($config->api_key);
        $res = $client->publish("planv2:{$planv2_id}", $message);
        if(!empty($res->error)){
            SLog::write($res); return false;
        }
        return true;
    }
```

**Comment by hetao29** [comment] 2019-04-15 11:44
![image](https://user-images.githubusercontent.com/8010298/56130216-e314f980-5fb6-11e9-9b13-a69af088ce93.png)
![image](https://user-images.githubusercontent.com/8010298/56130228-e9a37100-5fb6-11e9-8756-c2dbf4ccb999.png)
![image](https://user-images.githubusercontent.com/8010298/56130240-ef995200-5fb6-11e9-941c-43eb5697e672.png)

**Comment by FZambia** [comment] 2019-04-15 11:46
Could you also share your full Centrifugo configuration?

**Comment by hetao29** [comment] 2019-04-15 11:46
```json
{
	"api_key": "850ef89ef7ca8a6abe9e936462c6612b",
	"secret": "c65c0c085bbe98fce934cd88facae325",
	"admin_password": "admin_yunke",
	"admin_secret": "admin_secret_yunke",

	"engine":"redis",
	"redis_host":"127.0.0.1",
	"redis_port":"6380",
	"redis_prefix":"centrifugov2",

	"namespaces": [
		{
			"name": "test1",
			"publish": true,
			"presence": true,
			"join_leave": true,
			"anonymous":true,
			"recover": true,
			"history_size": 30,
			"history_lifetime": 300000
		},
		{
			"name": "planv2",
			"publish": true,
			"presence": true,
			"join_leave": true,
			"anonymous":true,
			"recover": true,
			"websocket_compression":true,
			"history_size": 50,
			"history_lifetime": 300000
		}
	]
}
```

**Comment by hetao29** [comment] 2019-04-15 11:47
```bash
sudo nohup /data/message/bin/centrifugo -p 8012 --name messagev2_01 --pid_file=/tmp/messagev2_01.pid --config=/data/message/bin/configv2.json --admin --log_file=/data/log/messagev2.log >> /data/log/messagev2.nohup.log 2>&1 &
```

**Comment by hetao29** [comment] 2019-04-15 11:47
```bash
/data/redis/bin/redis-server --port 6380
/data/redis/bin/redis-server version
25536:C 15 Apr 2019 19:47:42.680 # Fatal error, can't open config file 'version'
```

**Comment by FZambia** [comment] 2019-04-15 12:42
@hetao29 thanks, I'll take a look and will try to reproduce. In v2.2.0 new algorithm that checks client state was added, looks like this is somehow related to it.

Btw, Centrifugo v2 does not have `recover` option for channels. It's called `history_recover` - see https://centrifugal.github.io/centrifugo/server/configuration/. There is a chance that if you change it to `history_recover` things will start working for you. Though it should work properly even with your current configuration too.

**Comment by thinkwelltwd** [comment] 2019-04-15 15:15
>  When I publish message from server , the client with the same channel websocket will be reset.

I had the same problem last week when upgrading from 1.8 -> 2.2, and upgrading to the latest release of [centrifuge-js](https://github.com/centrifugal/centrifuge-js).  I was using the in-memory transport so that takes Redis out of the picture.

I finally downgraded Centrifugo to 2.1 and then things worked. I didn't file a bug report because I assumed that the centrifuge-js package had an incompatibility with 2.2 that would be resolved in a later update.

So anyway, I'm up and going. Just thought I'd post my experience if a confirmation would be helpful.  My centrifugo config is:

```
log_level: info
port: 10100
secret: <secret>
api_key: <key>
web: false

name: filter_console
history_size: 10
history_lifetime: 30
join_leave: true
publish: true
presence: true
watch: true
insecure: false
anonymous: false
namespaces:
  - name: public
  - name: filter_access
  - name: filter_errors
  - name: filter_tls
  - name: ksync
```

Thanks for the centrifuge ecosystem!

**Comment by FZambia** [comment] 2019-04-15 16:22
@thinkwelltwd hello, thanks! I reproduced an issue, will try to fix it ASAP.

**Comment by FZambia** [comment] 2019-04-15 18:45
Just released v2.2.1 which I believe should fix an issue. @hetao29 could you please to check it out?

**Comment by thinkwelltwd** [comment] 2019-04-15 22:08
v2.2.1 is working for me! :rocket: :100: :grin:

**Comment by hetao29** [comment] 2019-04-16 08:04
> Just released v2.2.1 which I believe should fix an issue. @hetao29 could you please to check it out?

Yes, it's works, thanks very much.

**Closed** 2019-04-16 08:04 UTC

**Comment by FZambia** [comment] 2019-04-16 08:16
@hetao29 thanks for report!

**Comment by hetao29** [comment] 2019-04-16 12:28
@FZambia v2.2.1 with redis 5.x is OK，with redis 3.0.x is not OK.

**Comment by FZambia** [comment] 2019-04-16 12:36
As I said above you need Redis at least 3.2.x for Centrifugo
