### ISSUE TITLE
session not in open state

### ISSUE THREAD

**Issue by visrs** [centrifugal/centrifugo#158] opened 2017-02-17 07:20 UTC
[I]: 2017/02/16 08:22:26 New SockJS session established with uid 20bda3bf-fec0-4439-9708-1737cf0704db
[I]: 2017/02/16 08:56:05 error sending to 20bda3bf-fec0-4439-9708-1737cf0704db sockjs: session not in open state

**Comment by FZambia** [comment] 2017-02-17 07:25
The same as #157

**Comment by FZambia** [comment] 2017-02-17 07:26
Hmm, looks like you are using old Centrifugo right?

**Comment by visrs** [comment] 2017-02-17 07:35
Yes，1.5.1

**Comment by FZambia** [comment] 2017-02-17 08:40
Closing as duplicate of #157 . I also suggest you to upgrade to latest Centrifugo version.

**Closed by FZambia** 2017-02-17 08:40 UTC
